#!/bin/sh

# % ./forward2docker <path to Dockerfile>

die() {
    echo "$@" >&2
    exit 1
}

log() {
    echo "[forward2docker] $@" >&2
}

set -e

dockerfile=$1

test -f "$dockerfile" || die "Usage: $0 <dockerfile>"

test -f "$HOME/.forward2docker/profile" && . "$HOME/.forward2docker/profile"

BOOT2DOCKER=${BOOT2DOCKER-$(dirname $0)/boot2docker}
PORT_OFFSET=${PORT_OFFSET-10000}

__ssh() {
  ssh_args="$@"

  expect -c "
spawn $BOOT2DOCKER ssh $ssh_args
expect password:
send \"tcuser\\r\"
interact
"
}

### Initialize boot2docker

if [ ! -x $BOOT2DOCKER ]; then
    curl -# https://raw.github.com/steeve/boot2docker/master/boot2docker > boot2docker
    chmod +x boot2docker
fi

if ! $BOOT2DOCKER status; then
    $BOOT2DOCKER init || true
    $BOOT2DOCKER up   || true
    $BOOT2DOCKER status
fi

export DOCKER_HOST=localhost

log 'boot2docker initialized.'

### Set up image/container

log 'Building image...'

dockerfile_dir=${TMPDIR-/tmp}/forward2docker.$$.$RANDOM
mkdir -p "$dockerfile_dir"
cp "$dockerfile" "$dockerfile_dir/Dockerfile"
docker build "$dockerfile_dir"

image=$(docker images -q | head -1)

log 'Starting container...'

container=$(

docker run -d "$image"

)

port_forwards=$(

docker inspect -format='{{with $n:=.NetworkSettings}}{{range $port,$:=$n.Ports}}{{$n.IPAddress}} {{$port}}{{"\n"}}{{end}}{{end}}' "$container" | while read addr port; do
    if [ -n "$port" ]; then
        port=${port%/tcp}
        local_port=$(($port + $PORT_OFFSET))
        echo "-L$local_port:$addr:$port"
        log "$container: listen on port $local_port"
    fi
done

)

log 'Starting port forwarding...'

__ssh $port_forwards -- echo Success! '&&' docker logs -f "$container" || true

log 'Cleaning up container...'

docker stop "$container" > /dev/null || true
docker kill "$container" > /dev/null || true
docker rm   "$container" > /dev/null || true
